language: node_js

node_js:
  - 12
  - 14

cache:
  npm: true

install:
  - npm ci

script:
  - npm run build:prod
  - npm run test
  - npm run size

after_success:
  - npm run test:send-coverage-to-coveralls
